### ISSUE TITLE
Unhandled stream error in pipe when using compilerFlags

### ISSUE THREAD

**Issue by obihill** [steida/gulp-closure-compiler#32]
I am using gulp-closure-compiler like so:

```javascript
.pipe(gp_closure_compiler({
                compilerPath: './bower_components/closure-compiler/compiler.jar',
                fileName: 'kquery.cc.js',
                compilerFlags: {
                    compilation_level: 'ADVANCED_OPTIMIZATIONS',
                    only_closure_dependencies: true,
                    warning_level: 'VERBOSE'
                }
            }))```

However, I am getting the following error

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: spawn OK
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

When I remove the `compilerFlags` option, I don't get any errors.

Any ideas?

**Comment by steida** [comment]
I would start with one flag, then add more, to figure out which flag is broken? Not sure why it happens.

**Comment by obihill** [comment]
I did use only the `compilation_level` flag and I still get the same error.

**Comment by steida** [comment]
try to run compiler from command line, read gulp-closure-compiler source to see how
