### ISSUE TITLE
Unexpected strict mode reserved word?

### ISSUE THREAD

**Issue by chihuahua** [steida/gulp-closure-compiler#53]
```
chizeng-macbookpro:meep chizeng$ gulp
/Users/chizeng/Desktop/meep/node_modules/google-closure-compiler/lib/gulp/index.js:106
          let outputFiles;
          ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/chizeng/Desktop/meep/node_modules/google-closure-compiler/index.js:26:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Is this just due to the version of node I use?

My version information:

```
chizeng-macbookpro:meep chizeng$ node -v;npm -v;gulp -v
v0.12.5
3.8.9
[00:59:23] CLI version 3.9.1
[00:59:23] Local version 3.9.1
```

**Comment by chihuahua** [comment]
Oh, I need ES6 support. I fixed this by calling `require('harmonize')();` before `require('gulp-closure-compiler')`.

**Comment by blackadder1000** [comment]
I am having a similar issue but don't understand what I need to do to fix...

Adding the line 

var closureCompiler = require('gulp-closure-compiler');

causes

C:\MyProject\node_modules\gulp-closure-compiler\node_modules\google-closure-compiler\lib\gulp\index.js:106
          let outputFiles;
          ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Devcode\client\Forms\Forms\CF\node_modules\gulp-closure-compiler\node_modules\google-closure-compiler\index.js:26:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Anyone got any ideas what I need to do?

**Comment by chihuahua** [comment]
gulp-closure-compiler requires ES6 support. Try installing harmonize and calling `require('harmonize')();` before requiring gulp-closure-compiler.
