### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by blackadder1000** [steida/gulp-closure-compiler#54]
Hi All

Adding the line

var closureCompiler = require('gulp-closure-compiler');

causes

C:\MyProject\node_modules\gulp-closure-compiler\node_modules\google-closure-compiler\lib\gulp\index.js:106
let outputFiles;
^^^
SyntaxError: Unexpected strict mode reserved word
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Devcode\client\Forms\Forms\CF\node_modules\gulp-closure-compiler\node_modules\google-closure-compiler\index.js:26:19)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)

Anyone got any ideas what I need to do?

**Comment by zarov** [comment]
Hello,

By default the compiler thinks that he reads ES3. If you want to use a more modern syntax (such as ES6), [add the corresponding flag in your configuration](https://github.com/steida/gulp-closure-compiler/blob/master/flags.txt#L145-L150). For example : 

```js
gulp.task('default', function() {
  return gulp.src(['main.js', 'src/**/*.js', 'bower_components/closure-library/closure/goog/**/*.js'])
    .pipe(closureCompiler({
      compilerPath: 'bower_components/closure-compiler/compiler.jar',
      fileName: 'build.js',
      compilerFlags: {
        language_in: 'ECMASCRIPT6'
      }
    }))
    .pipe(gulp.dest('dist'));
});
```

**Comment by blackadder1000** [comment]
Hi, I tried this but I still have the same issue.  Do I have to tell Visual Studio somewhere to use ECMASCRIPT6 for when its reading the GULP file?

Regards

Mike
