### ISSUE TITLE
Externs with Glob pattern

### ISSUE THREAD

**Issue by aholla** [steida/gulp-closure-compiler#9]
Hi, Im trying to reference my externs folder using a 'glob' but it is throwing an error:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Command failed: ERROR - Cannot read: ..\deploy\js\libs\**\*.js

1 error(s), 0 warning(s)

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)
```

my code is:
```
externs                    : [ '../deploy/js/libs/**/*.js' ],
```

Am I doing this wrong?

If I reference a file directly it works but I have a bunch of files. 
```
externs                    : [ '../deploy/js/libs/subfolder/examplefile.js' ], // this works
```

Thanks.

**Comment by hachr** [comment]
PR @ https://github.com/steida/gulp-closure-compiler/pull/11

**Comment by steida** [comment]
LGTM, Thank you.
